version: '3'

services:
  php:
    build: ./docker/php
    volumes:
    - .:/var/www/html
    working_dir: /var/www/html

  nginx:
    image: nginx:stable
    ports:
    - 80:80
    links:
    - php
    volumes:
    - .:/var/www/html
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
